### ISSUE TITLE
[BackEnd] Signup시 user_id duplication 확인

### ISSUE THREAD

**Issue by whitedelay** [skkuse02/2019fall_42class_team5#2]

**Comment by bellahj0323** [comment]
200 OK

**Comment by bellahj0323** [comment]
> _No description provided._

hi

**Comment by bellahj0323** [comment]
[https://github.com/skkuse02/2019fall_42class_team5/blob/master/Server/routes/login.js](url)
front-end랑 통신하면서 test 추가적으로 필요!

`connection.query('SELECT COUNT(*) as dup FROM user WHERE user_id= ?', users.user_id`
`if(results[0].dup==0){ `
` connection.query('INSERT INTO user SET ?' , users, function (error, results, fields)  `
